export const Products = [
  {
    id: 1,
    name: "Apple iPhone 15 (128 GB Storage, Pink)",
    price: 79900,
    rating: 4.5,
    image: "/img1.jpg",
  },
  {
    id: 2,
    name: "Apple iPhone 15 Pro (128 GB Storage, Titanium)",
    price: 134900,
    rating: 4.4,
    image: "/img2.jpg",
  },
  {
    id: 3,
    name: "Apple iPhone 14 (128 GB, Purple)",
    price: 69900,
    rating: 3.9,
    image: "/img3.jpg",
  },
  {
    id: 4,
    name: "boAt Airdopes Bliss Wireless Earbuds (Cool Blue)",
    price: 2099,
    rating: 4.0,
    image: "/img4.jpg",
  },
  {
    id: 5,
    name: "boAt Airdopes Unity Wireless Earbuds (Black)",
    price: 5999,
    rating: 4.6,
    image: "/img5.jpg",
  },
  {
    id: 6,
    name: "boAt Airdopes 131 Wireless Buds(Cherry)",
    price: 2990,
    rating: 3.0,
    image: "/img6.jpg",
  },
  {
    id: 7,
    name: "Fujifilm instax Mini 11 Instant Camera (Charcoal Grey)",
    price: 7999,
    rating: 4.3,
    image: "/img7.jpg",
  },
  {
    id: 8,
    name: "GoPro HERO11 Black Mini Waterproof Action Camera (Black)",
    price: 41500,
    rating: 4.5,
    image: "/img8.jpg",
  },
  {
    id: 9,
    name: "Canon EOS 200D II DSLR Camera EF-S 18 - 55 mm IS STM Lens",
    price: 68995,
    rating: 4.5,
    image: "/img9.jpg",
  },
];
